image: tetraweb/php

before_script:
  - apt-get update
  - apt-get install zip unzip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - apt-get update -qy
  - apt-get install -y lftp

build:
  script:
    - php composer.phar install

stage_deploy:
  script:
    - set ssl:verify-certificate no
    - lftp -e "open lextorg.myjino.ru; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .gitignore -X .gitlab-ci.yml --reverse --verbose --delete . domains/wowrp.sneakbug8.ru/; bye"